version: '3.7'

services:
  db_postgres:
    container_name: db_app
    image: postgres:11.2
    volumes:
      - db_postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  
volumes:
  db_postgres:
